### ISSUE TITLE
Skrells sem as genitals.

### ISSUE THREAD

**Issue by Schwaglord** [Beat-Station/Beat-Station#16]
Os skrells não tem seus genitals.

Não é exatamente um bug, está mais pra um erro comum.

Acredito que era pra eles a possuir os seus genitals, pois aparentemente eles possuem diferenças em gênero e tal.

Não é muito ruim, mas pode causar um certo incômodo.

**Steps to reproduce the problem**:
1. Entrar como skrell.
2. Falhar miseravelmente ao usar o interact.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Acredito que uma coisa dessa seja possível resolver fácilmente, sem gerar nenhum conflito/discussão.
Também não tem nada dizendo canonicamente que os skrells são neutros em relação a gênero(apesar de ser QUASE iguais), afinal de contas.

**Comment by Schwaglord** [comment]
Estarei aberto pra debates aqui, visto que o link do discord no MOTD expirou.

**Comment by davipatury** [comment]
https://discord.gg/JVbQmS3
Convite para o servidor do Discord.
