### ISSUE TITLE
Não da para remover roupas, handcuffs, e painel de ERP não aparece.

### ISSUE THREAD

**Issue by Avuds** [Beat-Station/Beat-Station#29]
**Problem Description**: Painel de ERP não aparece, e não dá para remover roupas ou ligar internals.
What is the problem?

**What did you expect to happen**: Painel de ERP aparecer, poder remover handcuffs ou roupas.
Why do you think this is a bug?

**What happened instead**: Nada
How is what happened different from what you expected?

**Why is this bad/What are the consequences:** Não dá para remover handcuffs de um criminoso que já cumpriu seu tempo, não dá para roubar objetos de alguém.
Why do you think this is an important issue?

**Steps to reproduce the problem**: Abrir um servidor, tentar tirar a roupa ou handcuff de alguém ou abrir o painel ERP, nada acontecer.
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by davipatury** [comment]
Acredito que seja um caso isolado, porque no servidor está funcionando certinho. Se realmente for um bug, precisamos de mais informações pra poder analisá-lo.

**Comment by Avuds** [comment]
Tirar handcuffs e acessar o inventário foi consertado, mas o Painel ERP ainda não aparece em servers privado.

**Comment by Schwaglord** [comment]
o FF só tá desligado, o que tem que fazer é ligar ele

**Comment by davipatury** [comment]
Fixed by #30

**Comment by davipatury** [comment]
Para ativar o painel de ERP tu tem que ativar nas configurações.
