### ISSUE TITLE
problemas

### ISSUE THREAD

**Issue by vxreal** [Beat-Station/Beat-Station#34]
entao, eu tava jogando na estaçao ne, e depois de um tempo, eu achei uma menina, e decidi fazer aquela coisinha que a gente aprende no quinto ano da escola ( ͡° ͜ʖ ͡°), mas quando fui ver aquele menu com o blowjob e essas coisa, nao apareceu nada, agente ficou sem transar, mas eu espero que voces possam arrumar! hackers experientes!

**Comment by davipatury** [comment]
o jogo tem um sistema que menores de 18 nao podem pegar no piu piu do amigo

**Comment by davipatury** [comment]
desculpa

**Comment by vxreal** [comment]
ahnnn mas eu tenho 19, deixa :(
quem comanda isso?

**Comment by davipatury** [comment]
tem que mostrar o rg pra provar, sao regras da empresa
