### ISSUE TITLE
[Repostando] Brig Physician sem acesso

### ISSUE THREAD

**Issue by Kaduh45** [Beat-Station/Beat-Station#4]
**Descrição do problema:**
O Brig Physician não tem acesso a brig, as maint e não consegue abrir o armário na sala dele

**O que você esperava que acontecesse:** 
Ele ter acesso

**O que ocorreu:**
Ele não tem acesso, acaba se tornado um medico comum

**Por quê você acha que isso é ruim?**
Porque ele tem como objetivo de cuidar dos segurança e prisioneiros.

**Como reproduzir o problema:**
Ir de Brig Physician e tentar abrir as portas da Brig

P.S. Alguém já fez a denuncia mas ficou no outro GibHub só estou refazendo aqui
P.S.2 E minha primeira vez no GibHub estou aprendendo desculpa qual quer coisa

**Comment by Kaduh45** [comment]
Bom no link do código dos da security relacionado ao Brig Physician:
https://github.com/Beat-Station/Beat-Station/blob/master/code/game/jobs/job/security.dm#L194-L205

Observe que na linha 203 está faltando alguns acesso... deveria ser algo parecido com a 204.

Nota-se que o acesso a química foi algo adicionado para facilita a vida dos médicos em geral, espero que continue assim pois é difícil depender de um químico quando o paciente precisa de mannitol.

**Comment by Tguara** [comment]
Nota: os acessos dele são:  Brig, Medbay, Operating Theatre, Morgue

**Comment by HarmonycStalker** [comment]
Mas que belezura

**Comment by Kaduh45** [comment]
Eu tentei fazer uma sugestão no código mas não sei com posta aqui ;-;
Basicamente eu copiei a lista da linha 204 na 203 mantendo o que já tava

**Comment by HarmonycStalker** [comment]
ata

**Comment by Neotwr** [comment]
Nota: os acessos dele são: Brig, Medbay, Operating Theatre, Morgue
